### PR TITLE
Automatically switches the device after login from the frontend

### PR DESCRIPTION
**Pull request by Nathanllee1**
#42

### CODE REVIEW

**Comment by doorlay** [comment]
Looks good! Approving...

**Comment by esauerbo** [comment]
This will be very useful for development. Now that it automatically transfers the SDK, I think we should remove the instructions for transferring the playback. It may be confusing for users if they see that screen while their song is loading.

**Comment by BSilton26** [comment]
Yeah I agree with Emma, plus I didn't feel like the directions fit stylistically.

**Comment by Nathanllee1** [comment]
> Looks good! Approving...

Thanks!

**Comment by Nathanllee1** [comment]
> This will be very useful for development. Now that it automatically transfers the SDK, I think we should remove the instructions for transferring the playback. It may be confusing for users if they see that screen while their song is loading.

I implemented that in a later pull request! Thanks

**Comment by Nathanllee1** [comment]
> Yeah I agree with Emma, plus I didn't feel like the directions fit stylistically.

Thanks for the feedback!

**Pull request merged**
